[package]
name = "calculator-backend"
version = "0.1.15"
edition = "2021"
license = "MIT OR Apache-2.0"
build = "build.rs"
description = "A simple calculator backend in Rust"

[dependencies]
libc = "0.2"

[build-dependencies]
cc = "1.2.0"
